services:
  backend:
    build:
      context: ./backend
    container_name: twinviz_backend
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - ./backend/uploads:/app/uploads
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on: []
  
  frontend:
    build:
      context: ./frontend
    container_name: twinviz_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
  
