name: Build and Deploy Portfolio Apps

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: [twinviz-3d-builder, ai-interview-coach, auto-flow-engine, career-copilot-ai, habitwise-ai, freelance-finance-tracker, agro-watch-iot, fitmanager-app, smartnotes-ai, idea-validator-ai]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        if: env.DOCKERHUB_USERNAME != ''
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        if: env.DOCKERHUB_USERNAME == ''
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push ${{ matrix.app }}
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.app }}
          push: true
          tags: |
             ${{ env.DOCKERHUB_USERNAME != '' && format('{0}/{1}:latest', toLower(env.DOCKERHUB_USERNAME), matrix.app) || format('ghcr.io/{0}/{1}:latest', toLower(github.repository_owner), matrix.app) }}
          cache-from: type=registry,ref=${{ github.repository_owner }}/${{ matrix.app }}:buildcache
          cache-to: type=inline
